version: '3.7'
networks:
  monitoring:
  
services:
  orbiter:
    image: leostarcevic/orbiter:master
    command: daemon
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
